# env_config
# satellite
sat_num: 126
satA_num: 108
satB_num: 9
satC_num: 9
n_sat: 20
n_state: 3
n_actions: 2
# action

# state
state_size:
  sat:
  task: 2
  inr:

#seed
seed: 12315

#SkyMapStandard
nside: 128
