# env_config
# satellite
sat_num: 126
satA_num: 108
satB_num: 9
satC_num: 9
n_sat: 4
n_state: 3
n_actions: 2
h: 600000
Re: 6371393
Omega: [0, 0, 0, 0]  # 升交点赤经
omega: [30, 30, 30, 30]  # 近地点幅角
mean_ano: [0, 90, 180, 270]  # 平近点角
e: 0  # 离心率
i: [43, 30, 30, 22]  # 轨道倾角
sun_avoid_angle: 75  # 太阳避免角
radius: 5

# action

# state
state_size:
  sat:
  task: 1
  inr:
task_dim: 64
npix: 768
t: 1000
week: 20  # 以第20周为例


#seed
seed: 12315

#SkyMapStandard
nside_std: 8

#ppo
kl_target: 0.02
minibatch_size: 32
gamma: 0.9
ent_coef: 0.001
vf_coef: 0.5
num_nn: 128
critic_std: 1
actor_std: 0.01
learning_rate: 5.0e-4
env_seed: 12315
num_epoch_steps: 30
total_timesteps: 2000000
num_env_steps: 128
num_update_steps: 4
gae_lambda: 0.95
max_grad_norm: 0.5
clip_coef: 0.2
save_frequency: 10240
mode: train
test_eps: 20
model_path: runs/ppo_train_20230608_23:09:37/model/checkpoint20230609_03:38:02.pt

# Trick
norm_adv: True
anneal_rate: True
use_reward_scaling: True

# email
sender: katniss5050@126.com
receiver: yinxiaodan21@mails.ucas.ac.cn
subject: "任务完成提醒"  # 邮件主题

# ABC
NP: 200
maxCycle: 150
limit: 50
runtime: 3
qtdm_show: False
modified: True
greedy_init: True
num_processes: 15

# problem
simple: True
factor: 3