# env_config
# satellite
sat_num: 126
satA_num: 108
satB_num: 9
satC_num: 9
n_sat: 1
n_state: 3
n_actions: 2
# action

# state
state_size:
  sat:
  task: 2
  inr:
npix: 196608
t: 1000
num_epoch_steps: 50

#seed
seed: 12315

#SkyMapStandard
nside: 128
