# env_config
# satellite
sat_num: 126
satA_num: 108
satB_num: 9
satC_num: 9
n_sat: 2
n_state: 3
n_actions: 2
# action

# state
state_size:
  sat:
  task: 1
  inr:

npix: 12288
t: 1000
num_epoch_steps: 1000

#seed
seed: 12315

#SkyMapStandard
nside_std: 32

#ppo
kl_target: 0.1
minibatch_size: 32
gamma: 0.9
ent_coef: 0.001
vf_coef: 0.5
num_nn: 128
critic_std: 1
actor_std: 0.01
learning_rate: 5e-4
env_seed: 12315

