# env_config
# satellite
sat_num: 126
satA_num: 108
satB_num: 9
satC_num: 9
n_sat: 2
n_state: 3
n_actions: 2
# action

# state
state_size:
  sat:
  task: 1
  inr:

npix: 196608
t: 1000


#seed
seed: 12315

#SkyMapStandard
nside_std: 128

#ppo
kl_target: 0.02
minibatch_size: 32
gamma: 0.9
ent_coef: 0.001
vf_coef: 0.5
num_nn: 128
critic_std: 1
actor_std: 0.01
learning_rate: 5.0e-4
env_seed: 12315
num_epoch_steps: 1000
total_timesteps: 2000000
num_env_steps: 128
num_update_steps: 4
gae_lambda: 0.95
max_grad_norm: 0.5
clip_coef: 0.2
save_frequency: 10240
mode: train
test_eps: 20
model_path: runs/ppo_train_20230608_23:09:37/model/checkpoint20230609_03:38:02.pt

# Trick
norm_adv: True
anneal_rate: True
use_reward_scaling: True